version: "3.9"

services:
  go-backend:
    container_name: go-backend
    build: ./go-backend/
    networks:
      - client
      - grpc
      - db
    ports:
      - "8000:8000"

  python-backend:
    build: ./python-backend/
    container_name: python-backend
    networks:
      - grpc

networks:
  client: {}
  grpc:
    name: grpc
  db: {}
