version: "3.9"

services:
  go-backend:
    container_name: go-backend
    build: ./go-backend/
    networks:
      - client
      - grpc
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./go-backend/:/app
    depends_on:
      - redis

  python-backend:
    build: ./python-backend/
    container_name: python-backend
    stop_signal: SIGINT
    networks:
      - grpc

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    networks:
      - client

  redis:
    image: "redis:7"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - db

networks:
  client: {}
  grpc: {}
  db: {}

volumes:
  redis-data: {}
