import Header from '@/components/Header'
import './globals.css'
import NavDrawer from '@/components/nav-drawer'
// import { atom } from 'jotai'

export const metadata = {
  title: 'Carz',
  description: 'Generated by create next app',
}

// const navVisibility = atom(false)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-neutral-100 text-neutral-900 h-screen flex">
          <NavDrawer />
          <div className="flex-grow">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
