import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-neutral-50 text-neutral-700 h-screen shadow-neutral-200">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
