# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import text_generate_pb2 as text__generate__pb2


class TextGenerateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCarReview = channel.unary_unary(
            "/text_generate.TextGenerateService/GenerateCarReview",
            request_serializer=text__generate__pb2.GenerateReviewReq.SerializeToString,
            response_deserializer=text__generate__pb2.ResString.FromString,
        )
        self.GenerateBlogSummarization = channel.unary_unary(
            "/text_generate.TextGenerateService/GenerateBlogSummarization",
            request_serializer=text__generate__pb2.GenerateBlogSummarizationReq.SerializeToString,
            response_deserializer=text__generate__pb2.ResString.FromString,
        )


class TextGenerateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCarReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateBlogSummarization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TextGenerateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateCarReview": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateCarReview,
            request_deserializer=text__generate__pb2.GenerateReviewReq.FromString,
            response_serializer=text__generate__pb2.ResString.SerializeToString,
        ),
        "GenerateBlogSummarization": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateBlogSummarization,
            request_deserializer=text__generate__pb2.GenerateBlogSummarizationReq.FromString,
            response_serializer=text__generate__pb2.ResString.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "text_generate.TextGenerateService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TextGenerateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCarReview(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/text_generate.TextGenerateService/GenerateCarReview",
            text__generate__pb2.GenerateReviewReq.SerializeToString,
            text__generate__pb2.ResString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GenerateBlogSummarization(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/text_generate.TextGenerateService/GenerateBlogSummarization",
            text__generate__pb2.GenerateBlogSummarizationReq.SerializeToString,
            text__generate__pb2.ResString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
